### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 1386: invalid start byte

### ISSUE THREAD

**Issue by robertclerc** [sebriois/biomart#19]
Hi, 

I try to print filters of my database but I have an error and i can't resolve them : 

```
import os
import pprint as pp
from biomart import BiomartServer

server = BiomartServer( "http://feb2014.archive.ensembl.org/biomart/" )
gene = server.datasets['hsapiens_gene_ensembl']
print "gene",gene
pp.pprint(gene.show_filters()) # uses pprint
```

>>>gene Homo sapiens genes (GRCh37.p13)

Traceback (most recent call last):
  File "ensembl.py", line 55, in <module>
    pp.pprint(gene.show_filters(),width=1) # uses pprint
  File "/home/clerc/.local/lib/python2.7/site-packages/biomart/dataset.py", line 68, in show_filters
    pprint.pprint(self.filters)
  File "/home/clerc/.local/lib/python2.7/site-packages/biomart/dataset.py", line 64, in filters
    self.fetch_filters()
  File "/home/clerc/.local/lib/python2.7/site-packages/biomart/dataset.py", line 82, in fetch_filters
    line = line.decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 1386: invalid start byte

**Comment by robertclerc** [comment]
If I use this database, it's ok : 
`
gene = server.datasets[u'hsapiens_gene_vega']`

**Comment by llrs** [comment]
You seem to use python 2.7 instead of python 3.x, but I am unsure if this is a reason of your error

**Comment by krassowski** [comment]
I had similar issue with biomart hosted by Ensembl, with different dataset though. I've published a potential fix to the problem on my fork in a separate branch: [github.com/krassowski/biomart/tree/fix/utf8-ensembl](https://github.com/krassowski/biomart/tree/fix/utf8-ensembl). If you find it working and useful I will issue a pull request.

When retrieving list of filters and allowed values of these, diseases names are read from biomart service (for some datasets). These names of diseases have some characters which were incorrectly encoded in UTF-8. You can find the character which was causing the problem by looking up 1386th character [here](http://feb2014.archive.ensembl.org/biomart//martservice?type=filters&dataset=hsapiens_gene_ensembl). My fix forces python decoder to simply ignore all problematic characters.
