### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by mashu** [sebriois/biomart#20]
I am trying to fetch some data from

`
server = BiomartServer("http://mar2016.archive.ensembl.org/biomart/martview")
`

However I get error
`
Traceback (most recent call last):
  File "./importBiomart.py", line 29, in <module>
    server = BiomartServer("http://mar2016.archive.ensembl.org/biomart/martview")
  File "/usr/local/lib/python2.7/dist-packages/biomart/server.py", line 27, in __init__
    self.assert_alive()
  File "/usr/local/lib/python2.7/dist-packages/biomart/server.py", line 48, in assert_alive
    self.get_request()
  File "/usr/local/lib/python2.7/dist-packages/biomart/server.py", line 103, in get_request
    r = requests.get(self.url, proxies = proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 111, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
`

Please help, pretty urgent.

**Comment by mashu** [comment]
After changing server url to martservice instead of martview it fetches something, but then sometimes dies and I get this error

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='mar2016.archive.ensembl.org', port=80): Max retries exceeded with url: /biomart/martservice?type=configuration&dataset=hsapiens_gene_ensembl (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff376c76590>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Is there a way to increase number of attempts or control that from outside of biomart library ?
I am fetching gene vs something for multiple different mappings.
I can't do that in single query, as it would be reduced set for some reason.

**Comment by ggirelli** [comment]
Try this:
```python
server = BiomartServer("http://mar2016.archive.ensembl.org/biomart")
```
Hope it helps :)
