### ISSUE TITLE
show_databases() not working (XML Parsing Broken?)

### ISSUE THREAD

**Issue by mkirsch17** [sebriois/biomart#25]
Hi,

A script using your API started returning the following error:

```
Traceback (most recent call last):

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-b441ad38d3c3>", line 1, in <module>
    server.show_datasets()

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/biomart/server.py", line 93, in show_datasets
    pprint.pprint(self.datasets)

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/biomart/server.py", line 62, in datasets
    self.fetch_datasets()

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/biomart/server.py", line 86, in fetch_datasets
    for database in self.databases.values():

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/biomart/server.py", line 56, in databases
    self.fetch_databases()

  File "/home/shiny/anaconda3/lib/python3.6/site-packages/biomart/server.py", line 70, in fetch_databases
    xml = fromstring(r.text)

  File "/home/shiny/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: undefined entity: line 36, column 5
```

All I'm trying to do is use show_databases() or show_datasets():

```
> import biomart
> server = biomart.BiomartServer("http://uswest.ensembl.org/biomart")
> server.show_datasets()
```

The API is up to date, I'm running Python 3.6.4. I noticed this error today, and the script was working as of about a week ago, so not sure when the actual change occurred (whatever that change may be). My script has been untouched in the time between then.

This script is pretty essential to my (and others') work flow, so it'd be great to get this resolved ASAP. Thanks!

**Comment by sebriois** [comment]
Hi,

I can't reproduce the error...

```bash
(biomart) [10:13:20] ~ -> python
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import biomart
>>> server = biomart.BiomartServer("http://uswest.ensembl.org/biomart")
>>> server.is_alive
True
>>> server.show_datasets()
{'acarolinensis_gene_ensembl': Anole lizard genes (AnoCar2.0),
 'acarolinensis_genomic_sequence': Anole lizard sequences (AnoCar2.0),
 'amelanoleuca_gene_ensembl': Panda genes (ailMel1),
 'amelanoleuca_genomic_sequence': Panda sequences (ailMel1),
 'amexicanus_gene_ensembl': Cave fish genes (AstMex102),
 'amexicanus_genomic_sequence': Cave fish sequences (AstMex102),
 'anancymaae_gene_ensembl': Ma's night monkey genes (Anan_2.0),
...
 'ttruncatus_gene_ensembl': Dolphin genes (turTru1),
 'ttruncatus_genomic_sequence': Dolphin sequences (turTru1),
 'vpacos_gene_ensembl': Alpaca genes (vicPac1),
 'vpacos_genomic_sequence': Alpaca sequences (vicPac1),
 'xmaculatus_gene_ensembl': Platyfish genes (Xipmac4.4.2),
 'xmaculatus_genomic_sequence': Platyfish sequences (Xipmac4.4.2),
 'xtropicalis_gene_ensembl': Xenopus genes (JGI 4.2),
 'xtropicalis_genomic_sequence': Xenopus sequences (JGI 4.2)}
>>> ^D
(biomart) [10:16:52] ~ -> pip list
Package    Version  
---------- ---------
biomart    0.9.2    
certifi    2018.1.18
chardet    3.0.4    
idna       2.6      
pip        9.0.3    
requests   2.18.4   
setuptools 39.0.1   
urllib3    1.22     
wheel      0.30.0   
```

It might be your anaconda setup that's messing things up? I don't know... Try making a new virtualenv only containing the biomart package to check that.

Sébastien

**Comment by MaxAlex** [comment]
I hit the same error just now and made a quick edit to the code to capture what Ensembl was returning, which got me this:

```
<html>
 <head>
  <style>
   body      { font-family: Luxi Sans, Helvetica, Arial, Geneva, sans-serif;
            font-size:90%; color: #336; background-color: #fff;
            padding: 0; margin: 0; border: 0; }

  
   div, span, p, li, dd, dt, th, td, pre, code, kbd { font-size: 1em; }
   h1              { font-size: 1.5em; }
   h2              { font-size: 1.2em; }
   h3              { font-size: 1.1em; }
   
   div.content   { padding: 20px; }
  </style>
 </head>
 <body>
  <div style="padding:5px;width:100%;height:60px;background-color:#333366">
   <img src="/e-ensembl.png" style="width:185px;height:45px" />
  </div>
  <div class="content">
  <h1>Server Status</h1>
    <p><img src="/exclamation_alert.png" alt="[!]" style="float:left;padding:0 10px;width:100px;height:89px" />
     The Ensembl mirror service you requested is temporarily unavailable. We are working to restore the service as soon as possible, and apologise for any inconvenience caused.</p>
    <p>For all enquiries, please <a href="http://www.ensembl.info/contact-us/">contact our HelpDesk</a>.</p>
    <div style="border:solid 1px #ccc; margin-top:20px; padding:10px">
      <h3>Alternative sites</h3>
      <p>Alternative Ensembl mirrors may be available when this site is down:</p>
      <ul id="mirrors">
        <li id="www"><a href="http://www.ensembl.org/index.html?redirect=no">[www.ensembl.org</a></li](https://www.ensembl.org</a></li)>
        <li id="useast-ensembl-org"><a href="http://useast.ensembl.org/index.html?redirect=no">useast.ensembl.org</a></li>
        <li id="uswest-ensembl-org"><a href="http://uswest.ensembl.org/index.html?redirect=no">uswest.ensembl.org</a></li>
        <li id="asia-ensembl-org"><a href="http://asia.ensembl.org/index.html?redirect=no">asia.ensembl.org</a></li>
      </ul>
    </div>
  <p>&copy; 2018 EMBL-EBI</p>
   
  </div>

<script src="/jquery.js"></script>
<script type="text/javascript">
  var me = window.location.href.replace(/^.*\/\//,'').replace(/\/.*$/,'').replace(/:.*?$/,'').replace(/\./g,'-');
  console.log(me);
  var okcount = 0;

  // Hide the current site in mirrors list
  $('#mirrors li').each(function(i,el) {
        var host, $el;
        $el = $(el);
        host = $el.attr('id');
        if (host == me) {
          $el.remove();
        }
  });

/* Needs reimplementing
  function prod(qcc) {
        $('#list .status').empty().removeClass('status-up').removeClass('status-down');
        $('#list .status').each(function(i,el) { $(el).text('checking'); });
        $.getJSON("/cgi/downtest.cgi",function(data) {
            $('#list a').each(function(i,el) {
              var host, status;
              host = $(el).data('host');
            if(data[host]) { status = "up"; } else { status = "down"; }
            var $status = $('.status',$(el).parents('tr'))
            $status.empty();
            $('<span>'+status+'</span>').appendTo($status);
            $status.addClass('status-'+status);
          });
          if(qcc) {
            if(data[me]) {
        okcount++;
              if(okcount>4) {
                $('.msg-back a').attr('href',"http://"+me+"/");
                $('.msg-back').css('display','block');
                $('.msg').css('display','none');
              }
            } else {
              $('.msg-back').css('display','none');
              $('.msg').css('display','block');
              okcount = 0;
            }
          }
        });
  }
  prod(0);
  setInterval(function() { prod(1); },20000); 
  */
</script>


 </body>
</html>
```

So it looks like this is just what happens when Biomart goes down. For anyone else encountering this issue, a quick fix is to change the mirror you're using (e.g. "useast.ensembl.org/biomart/" to "uswest.ensembl.org/biomart/") since mirrors should at least go down separately.
